### ISSUE TITLE
Live code reload

### ISSUE THREAD

**Issue by settinghead** [Rise-Vision/widget-preview#26]

**Comment by alanclayton** [comment]
@donnapep @stulees @rodrigopavezi should this be closed?

**Comment by donnapep** [comment]
@alanclayton I don't think so. This would be nice to have and a possible improvement.

**Comment by stulees** [comment]
@alanclayton I think all the enhancement issues open on this repo are worth keeping open.

**Comment by alanclayton** [comment]
@stulees I'm going to close for now so we are clear on what open issues are. I added a card to the backlog. https://trello.com/c/rle7hFms/1265-live-code-reload-for-widget-preview Thanks
