### ISSUE TITLE
Nicer params/additionalParams view

### ISSUE THREAD

**Issue by settinghead** [Rise-Vision/widget-preview#27]
@stulees: "A secondary representation of the params and additionalParams values in a more readable format would be nice for our testing. Eg.
up_cells=sheet
up_headerRows=2
up_fileID=0Av0wEY9sizgUdDVjN09uQTYwZHd3ZkU0dGh4TURLSHc
etc ..."

**Comment by alanclayton** [comment]
@stulees @donnapep @rodrigopavezi should this be closed?

**Comment by stulees** [comment]
@alanclayton It's an enhancement, does it need to be closed?

**Comment by alanclayton** [comment]
@stulees let's close it for now. Thanks
