### ISSUE TITLE
Configure Jenkins task for PR build

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/widget-preview#53]

**Comment by alanclayton** [comment]
@alex-deaconu @donnapep @stulees is this something we need to address?

**Comment by alex-deaconu** [comment]
@alanclayton would be nice, having this built automatically in CCI. However, from what I recall and from this discussion here #58 this repo cannot be built. We would need to fix that first to get it to CCI.

Thanks.

**Comment by alanclayton** [comment]
@alex-deaconu Thanks.  @donnapep @stulees @rodrigopavezi can you let me know what you want to do here? thanks

**Comment by stulees** [comment]
@alanclayton As @alex-deaconu mentioned, we'd need to address #58 first to ensure it's not an issue anymore or we have to fix it. Then we'd need to investigate the effort involved in a CCI build of this repo as it's a different kind of build to our other repos.

**Comment by rodrigopavezi** [comment]
Closing as the automated deployment has been implemented.
