### ISSUE TITLE
Allow data in Params and Additional Params to be copied

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/widget-preview#56]

**Comment by alanclayton** [comment]
@donnapep @stulees is this still an issue?

**Comment by stulees** [comment]
@alanclayton Yes and it's due to a bug in a dependency. It's one of our improvements to check on if the bug has since been fixed.

**Comment by rodrigopavezi** [comment]
@stulees could you point me out to the bug you are mentioning above so I can verify? cheers

**Comment by stulees** [comment]
@rodrigopavezi This is what I had previously found and mentioned on an older Trello card:

> From what I've been able to tell, it appears there is a bug with nw.js for cut/copy/paste on Mac - https://github.com/nwjs/nw.js/issues/1955 . There is a workaround mentioned in the thread, however it involves code being integrated directly with use of nw.js which isn't possible in widget-preview.

> widget-preview is built with nw-builder (https://github.com/nwjs/nw-builder) which builds a nw.js app for Mac, Windows, and Linux. It downloads the prebuilt binaries for a specified nw.js version and creates the necessary app.nw file and directories and copies the appropriate files per each OS directory.

> I tried running just the Angular app of widget-preview in a browser and cut/copy/paste works fine. So unfortunately, I don't see a fix for this. We'll have to keep an eye on the GH issue for nw.js.

**Comment by rodrigopavezi** [comment]
@stulees thanks. @alanclayton as @stulees stated above, we still cannot fix this issue as there is still no proper resolution for that bug. Should we leave it here open so we can come back time to time to check if there is a feasible resolution. cheers

**Comment by alanclayton** [comment]
@rodrigopavezi @stulees do either of you see this issue getting resolved given it has been a problem for more than a year?

**Comment by rodrigopavezi** [comment]
@alanclayton I don't see it. cheers

**Comment by stulees** [comment]
@alanclayton I don't either

**Comment by alanclayton** [comment]
@stulees @rodrigopavezi okay, I'm going to close this then. Thanks
