### ISSUE TITLE
Unable to install and run

### ISSUE THREAD

**Issue by jbearden0** [Rise-Vision/widget-preview#58]
I am trying to install and run on Ubuntu 14.04 and the instructions say to run the "nw" executable, but that doesn't exist in the install zip. The package contains:  icudtl.dat, libffmpegsumo.so,  nw.pak, and  rv-widget-dev-app. I tried to run "rv-widget-dev-app" but I get the error "error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory". Some sort of README would be nice, and extra points for information on what to do once it is up and running.

**Comment by jbearden0** [comment]
OK, so after some more research I ran "npm install -g nw", and what I believe I am supposed to do is run "nw widget-preview-linux32.zip", but when I do that nw complains that there is no package.json

**Comment by stulees** [comment]
@jbearden0 Thanks for raising the issue and apologies for a misleading README. Let me first clarify that you do not need to clone this repo and run a build to use this application. It is intended to be downloaded, unzipped, and installed to be run as an executable file. The application provides a way to assist in local development of your widget. 

Unfortunately, there do appear to be issues with installation on Ubuntu 14.04. We are aware of the problems and will be addressing them soon after a couple other current projects on the go. I'll inform you on any progress or updates here on this issue. Thanks

**Comment by alanclayton** [comment]
@stulees any reason we shouldn't get this queued up to be fixed?

**Comment by stulees** [comment]
@alanclayton Yes we could queue this up. I'm not entirely sure if there is still an issue as I updated nw-builder back in October which may have helped to resolve this issue.

**Comment by rodrigopavezi** [comment]
@alanclayton closing this issue. I tested the latest linux package and it worked on Ubuntu 14.04. cheers
